const NB_COLONNES = 7;
const NB_RANGEE = 6;
const RANGEE_DU_BAS = 5;
const CELLULE_VIDE = '';
const JETON_ROUGE = 'ROUGE';
const JETON_JAUNE = 'JAUNE';

export { NB_COLONNES, NB_RANGEE, RANGEE_DU_BAS, CELLULE_VIDE, JETON_ROUGE, JETON_JAUNE };
